image_root: ''
test_file: 'annotation/test/attr.json'
# OOD test set
#test_file: 'annotation/test/ucc.json'


train_file:  [
  'annotation/train/attr_0.json', 'annotation/train/attr_1.json',
  'annotation/train/attr_2.json', 'annotation/train/attr_3.json',
  'annotation/train/attr_4.json', 'annotation/train/attr_5.json',
  'annotation/train/attr_6.json', 'annotation/train/attr_7.json',
  'annotation/train/attr_8.json', 'annotation/train/attr_9.json',

  # 'annotation/train/attr_10.json', 'annotation/train/attr_11.json',
  # 'annotation/train/attr_12.json', 'annotation/train/attr_13.json',
  # 'annotation/train/attr_14.json', 'annotation/train/attr_15.json',
  # 'annotation/train/attr_16.json', 'annotation/train/attr_17.json',
  # 'annotation/train/attr_18.json', 'annotation/train/attr_19.json',

  # 'annotation/train/attr_20.json', 'annotation/train/attr_21.json',
  # 'annotation/train/attr_22.json', 'annotation/train/attr_23.json',
  # 'annotation/train/attr_24.json', 'annotation/train/attr_25.json',
  # 'annotation/train/attr_26.json', 'annotation/train/attr_27.json',
  # 'annotation/train/attr_28.json', 'annotation/train/attr_29.json',

  # 'annotation/train/attr_30.json', 'annotation/train/attr_31.json',
  # 'annotation/train/attr_32.json', 'annotation/train/attr_33.json',
  # 'annotation/train/attr_34.json', 'annotation/train/attr_35.json',
  # 'annotation/train/attr_36.json', 'annotation/train/attr_37.json',
  # 'annotation/train/attr_38.json', 'annotation/train/attr_39.json',

  # 'annotation/train/attr_40.json', 'annotation/train/attr_41.json',
  # 'annotation/train/attr_42.json', 'annotation/train/attr_43.json',
  # 'annotation/train/attr_44.json', 'annotation/train/attr_45.json',
  # 'annotation/train/attr_46.json', 'annotation/train/attr_47.json',
  # 'annotation/train/attr_48.json', 'annotation/train/attr_49.json',

  # 'annotation/train/attr_50.json', 'annotation/train/attr_51.json',
  # 'annotation/train/attr_52.json', 'annotation/train/attr_53.json',
  # 'annotation/train/attr_54.json', 'annotation/train/attr_55.json',
  # 'annotation/train/attr_56.json', 'annotation/train/attr_57.json',
  # 'annotation/train/attr_58.json', 'annotation/train/attr_59.json',

  # 'annotation/train/attr_60.json', 'annotation/train/attr_61.json',
  # 'annotation/train/attr_62.json', 'annotation/train/attr_63.json',
  # 'annotation/train/attr_64.json', 'annotation/train/attr_65.json',
  # 'annotation/train/attr_66.json', 'annotation/train/attr_67.json',
  # 'annotation/train/attr_68.json', 'annotation/train/attr_69.json',

  # 'annotation/train/attr_70.json', 'annotation/train/attr_71.json',
  # 'annotation/train/attr_72.json', 'annotation/train/attr_73.json',
  # 'annotation/train/attr_74.json',
]

## Text Encoder
text_config: 'config/config_bert.json'
text_encoder: '/root/autodl-tmp/saved_model/pretrained/bert-base-uncased'
siglip_pretrained: '/root/autodl-tmp/saved_model/siglip2/siglip2-origin-full-bs640.pt'

## Image Encoder
h: 224
w: 224

## Training
load_params: False
load_pretrained: True

max_words: 64
max_tokens: 64
eda_p: 1.0
erasing_p: 0.6

# SigLIP用大Batch的效果可能更好
batch_size_train: 160
batch_size_test: 120
batch_size_test_text: 150
batch_size_test_text: 150

embed_dim: 2048
itc_dp: 0.5
temp: 0.07
label_smooth: 0.2

## mlm loss
mask_prob: 0.25
max_masks: 10
skipgram_prb: 0.2
skipgram_size: 3
mask_whole_word: True

optimizer: {opt: adamW, siglip_lr: 0.0, mlp_lr: 1e-3, bert_lr: 1e-5, itm_lr: 1e-3, weight_decay: 0.01}
scheduler: {sched: step, lr: 1e-4, epochs: 15, num_warmup_steps: 500}

k_test: 128


be_hard: True
be_pose_img: False
pose_conv: True
